name: Terraform plan workflow

on:
  pull_request:
    types:
      - opened

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: "eu-west-2"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        working-directory: module03/infra
        run: |
          terraform fmt -check
      - name: Terraform init
        working-directory: module03/infra
        run: |
          terraform init
      - name: Terraform validate
        working-directory: module03/infra
        run: |
          terraform validate
      - name: Terraform plan
        id: plan
        working-directory: module03/infra
        run: |
          echo "stdout<<EOF" >> $GITHUB_OUTPUT
          terraform plan -no-color >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Comment plan on PR
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan
            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

permissions:
  id-token: write  # РАЗРЕШАЕТ запросить OIDC-токен у GitHub
  contents: read  # прочитать код репозитория
  pull-requests: write  # чтобы постить план в комментарий к PR
