name: Terraform plan workflow

on:
  pull_request:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: module03/infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: "eu-west-2"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: |
          terraform fmt -check
      - name: Terraform init
        run: |
          terraform init
      - name: Terraform validate
        run: |
          terraform validate
      - name: Terraform plan
        id: plan
        run: |
          terraform plan -no-color
      - name: Comment plan on PR
        uses: actions/github-script@v7
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          script: |
            const output = `#### Terraform Plan
            \`\`\`
            ${process.env.PLAN}
            \`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

permissions:
  id-token: write  # РАЗРЕШАЕТ запросить OIDC-токен у GitHub
  contents: read  # прочитать код репозитория
  pull-requests: write  # чтобы постить план в комментарий к PR
